##应用环境配置
#spring:
#  profiles:
#    active: @profile.active@
#    group:
#      "dev": devDB,devMVC
#      "pro": proDB,proMVC
#

#服务器端口
server:
  port: 80
#数据库连接配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: root
      password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: auto      #数据库主键自增
      table-prefix: tbl_ #数据库表名前缀
  #日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#debug: true

#logging:
#  group:
#    ebank: com.itheima.controller,com.itheima.service
#  level:
#    root: info
#    ebank: info
#  file:
#    name: server.log
#  logback:
#    rollingpolicy:
#      max-file-size: 4KB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
#  pattern:
#    console: "%d %clr(%5p) %n"
